apiVersion: v1
kind: Service
metadata:
  name: hello-aws-service
  labels:
    app: hello-aws
spec:
  type: NodePort
  selector:
    app: hello-aws
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080